### ISSUE TITLE
How can i change the urls of the database?

### ISSUE THREAD

**Issue by lvvittor** [afuh/rick-and-morty-api#32]
I am running the app in localhost. I have changed the exports.site = 'https://rickandmortyapi.com/api' to exports.site = 'http://localhost:8080/api' but its only changes the next/prev page in the info section. Is there a way to change all the url of the api to localhost instead of rickandmortyapi.com?

**Comment by afuh** [comment]
Hey,
since the urls are written in the database, there is no "easy" way to do it
In any case, the solution would be to run the database [locally](https://github.com/afuh/rick-and-morty-api#run-the-api-locally) and update the urls. 

You could update the urls in different ways: 
- With MongoDB: You could use the [$rename](https://docs.mongodb.com/manual/reference/operator/update/rename/index.html) operator with [updateMany()](https://docs.mongodb.com/manual/reference/method/db.collection.updateMany/)
- Use any MongoDB interface (like [Studio 3T](https://studio3t.com/)) and do it there.
- Go to the `/data` folder and in every `.bson` file, just select all `https://rickandmortyapi.com/api`and replace for `http://localhost:8080/api`

Hope this helps.

**Comment by lvvittor** [comment]
If you go to the /data folder and in every .bson file, just select all https://rickandmortyapi.com/apiand replace for http://localhost:8080/ you will get an error. I converted the .bson files to .jsons, chnaged the urls and imported them manually later. (But if you converted them later to .bson files and run npm run data doesn't work) Is there a way to import the json files into the database automatically with json files? (like the chars.metadata.json) when you run npm run data.

**Comment by afuh** [comment]
I asume you already solve this. 👍
