### ISSUE TITLE
Add more information to episode model

### ISSUE THREAD

**Issue by AlexMaguey** [afuh/rick-and-morty-api#33]
It would be nice if the episode model had more information like a plot, the name of the director, writers and actors, etc. (like imbd)

**Comment by afuh** [comment]
Hey, 
That's a pretty good idea. However since the episode schema is mostly used to support the characters schema, we hadn't thought about adding more data to it. 

I think adding the plot would be a nice addition. I'm not so sure about director, actors, etc. because we would prefer not to link outside the API. You are completely welcome to collaborate with the episode's plot.

Thanks!

**Comment by afuh** [comment]
I'm closing this due inactivity.
